#! /bin/sh
# /etc/init.d/ch-box-admin

### BEGIN INIT INFO
# Provides:          raspberry-wifi-conf
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to add wifi connections and update CH software
# Description:       A NodeJS application to add WiFI connectivity, add AP if necessary, and a place to update CH software
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting ch-box-admin service"
    cd /ch/current/www/ch-box-admin
    sudo /usr/bin/node server.js < /dev/null &
    echo $! > node.pid
    ;;
  stop)
    echo "Stopping ch-box-admin service"
    PIDFile=/ch/current/www/ch-box-admin/node.pid
    if [ -f $PIDFile ]; then
        sudo kill -9 $(cat $PIDFile)
        sudo kill -9 $(($(cat $PIDFile) + 1))
        sudo rm $PIDFile
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/ch-box-admin {start|stop}"
    exit 1
    ;;
esac

exit 0
